Try other test reporting for xunit/trx/dotnet

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -16,20 +16,27 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
+
       - name: Restore dependencies
         run: dotnet restore
+
       - name: Build
         run: dotnet build --no-restore
+
       - name: Test
         run: dotnet test --no-build --logger "trx;LogFileName=TestResults.xml"
-      - name: Install ReportGenerator
-        run: dotnet tool install -g dotnet-reportgenerator-globaltool
-      - name: Generate HTML Report
-        run: reportgenerator -reports:**/TestResults.xml -targetdir:TestResults -reporttypes:Html
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: .NET Tests
+          path: TestResults/TestResults.xml
+          reporter: trx
 
       - name: Publish Test Results
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: TestResults
-          path: TestResults
+          path: "**/TestResults"
